name = "zhiwei-daily-report-gen"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-09-18"
vars = {}

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"