name = "zhiwei-daily-report-content-gen"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-09-18"

[build]
command = "npm install && npm run re:build && npm run build"
[build.upload]
format = "service-worker"
