// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_json from "../node_modules/rescript/lib/es6/js_json.js";

function handleRequest(req) {
  var promiseJsonBody = req.json();
  return promiseJsonBody.then(function (body) {
                var value = Js_json.classify(body);
                if (typeof value === "number") {
                  return [];
                } else if (value.TAG === /* JSONArray */3) {
                  return value._0;
                } else {
                  return [];
                }
              }).then(function (val) {
              return new Response(val.join(","));
            });
}

export {
  handleRequest ,
  
}
/* No side effect */
